name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - ./

permissions:
  actions: read
  packages: write

jobs:
  push:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64, linux/arm64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/catsz/archean_pterodactyl:$(date +%s)
